#CONSTANTS

DEFAULT_PORT=10000

HEADER_LENGTH = 10

SERVER_TIMEOUT = 2
CONNECTION_TIMEOUT = 2
SEND_MESSAGE_TIMEOUT = 1
MESSAGE_QUEUE_TIMEOUT = 0.2
REQUEST_TIMEOUT = 50 #* 0.2sec
HOLE_PUNCHING_TIMEOUT = 20 #*SERVER TIMEOUT

DB_QUEUE_TIMEOUT = 2

NON_PEER_BOOK_CONNECTION_LIFETIME = 3 #that's how long a connection without UUID will live (this * connection_timeout)
if NON_PEER_BOOK_CONNECTION_LIFETIME == 0: NON_PEER_BOOK_CONNECTION_LIFETIME = float('inf')